app = 'drug-monitor-api'
primary_region = 'iad'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '8080'
  RAILS_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = './bin/rails server'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'